### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by cyrilf** [jkrmr/casper#3]
I have some issues with the syntax highlighting.

I just migrate from `whitespace` theme to `casper`.  
I've added this line (on my `_config.yml` file):
``` yml
highlight_js_color_theme: github
```

But at the end, here is the result..

![](http://i.imgur.com/YSPFX5e.png)

Do you have any idea why? As you can see the highlighting works, but I still have `~~~` displayed. This is the default post you gave.

Thanks in advance if you can help (or share your `_config.yml` file).

**Comment by jkrmr** [comment]
I'm using the default `_config.yml` generated by a new octopress installation. Are you using an up-to-date version of [Octopress 2](https://github.com/imathis/octopress)?

**Comment by cyrilf** [comment]
Yes, I think my version wasn't up to date or my `_config.yml` was too personalized.
Anyway, I tweaked a lot of things and it's working now (with another syntax highlighter).

Thanks for sharing this theme!
